#!/bin/bash
echo "🔧 Script to force GPU re-registration"
echo ""
echo "Run this on your GPU to force re-registration with new URL:"
echo ""
echo "# 1. Stop current miner"
echo "kill \$(cat heartbeat_bore.pid)"
echo ""
echo "# 2. Wait a few seconds"
echo "sleep 5"
echo ""
echo "# 3. Start again (will get new bore port and re-register)"
echo "./start_heartbeat_bore.sh"
echo ""
echo "# 4. Check new URL in logs"
echo "tail -f heartbeat_bore.out"
echo ""
echo "This will:"
echo "- Get a new bore.pub port"
echo "- Register with backend using new URL"
echo "- Backend will update its stored URL"